name: "Push to DockerHub"
description: "Build the image and push it to dockerhub"
inputs:
  dockerhub-login:
    required: true
    description: "Dockerhub login"
  dockerhub-token:
    required: true
    description: Dockerhub write token"
  app-name:
    required: true
    description: "The name of the app, must match the folder where app is stored"

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-login }}
        password: ${{ inputs.dockerhub-token }}
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:${{ inputs.app-name }}"
        push: true
        tags: ${{ inputs.dockerhub-login}}/raspberry-dev:coderunner3000-${{ inputs.app-name }}
