- name: lua5.1
  packages: ["lua5.1"]
  run_options:
    memory_limit: 128m
    cpus_limit: 0.25
    pids_limit: 8
    storage_limit: 64m
  steps:
    - name: "execute"
      image: "lua-runtime"
      command: ["lua5.1", "source"]
      timeout: 5
      stdout: "stdout.txt"
      stderr: "stderr.txt"

- name: racket
  packages: ["racket"]
  run_options:
    memory_limit: 256m
    cpus_limit: 0.5
    pids_limit: 8
    storage_limit: 64m
  steps:
    - name: "execute"
      command: ["racket", "source"]
      timeout: 15
      stdout: "stdout.txt"
      stderr: "stderr.txt"

- name: bash
  packages: ["bash"]
  run_options:
    memory_limit: 128m
    cpus_limit: 0.25
    pids_limit: 8
    storage_limit: 64m
  steps:
    - name: "execute"
      command: ["bash", "source"]
      timeout: 5
      stdout: "stdout.txt"
      stderr: "stderr.txt"

- name: c
  run_options:
    memory_limit: 256m
    cpus_limit: 1
    pids_limit: 8
    storage_limit: 64m
  packages: ["gcc", "musl-dev"]
  steps:
    - name: "compile"
      command: ["gcc", "-O2", "-x", "c", "source", "-o", "/home/evaluator_nobody/source.exe"]
      timeout: 1
      stdout: "stdout.txt"
      stderr: "stderr.txt"
    - name: "execute"
      command: ["/home/evaluator_nobody/source.exe"]
      timeout: 5
      stdout: "stdout.txt"
      stderr: "stderr.txt"

- name: python3
  packages: ["python3"]
  run_options:
    memory_limit: 128m
    cpus_limit: 0.25
    pids_limit: 8
    storage_limit: 64m
  steps:
    - name: "execute"
      command: ["python3", "source"]
      timeout: 5
      stdout: "stdout.txt"
      stderr: "stderr.txt"

- name: cpp23gcc
  run_options:
    memory_limit: 512m
    cpus_limit: 1
    pids_limit: 8
    storage_limit: 64m
  packages: ["gcc", "g++", "musl-dev"]
  steps:
    - name: "compile"
      command: ["g++", "-std=c++23", "-O2", "-x", "c++", "source", "-o", "/home/evaluator_nobody/source.exe"]
      timeout: 10
      stdout: "stdout.txt"
      stderr: "stderr.txt"
    - name: "execute"
      command: ["/home/evaluator_nobody/source.exe"]
      timeout: 5
      stdout: "stdout.txt"
      stderr: "stderr.txt"

